# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/chanz/OneDrive/桌面/15618_second_version

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/chanz/OneDrive/桌面/15618_second_version

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/chanz/OneDrive/桌面/15618_second_version/CMakeFiles /mnt/c/Users/chanz/OneDrive/桌面/15618_second_version/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/chanz/OneDrive/桌面/15618_second_version/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rubiksCube

# Build rule for target.
rubiksCube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rubiksCube
.PHONY : rubiksCube

# fast build rule for target.
rubiksCube/fast:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/build
.PHONY : rubiksCube/fast

Controller/Searcher/CubeSearcher.o: Controller/Searcher/CubeSearcher.cpp.o

.PHONY : Controller/Searcher/CubeSearcher.o

# target to build an object file
Controller/Searcher/CubeSearcher.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/CubeSearcher.cpp.o
.PHONY : Controller/Searcher/CubeSearcher.cpp.o

Controller/Searcher/CubeSearcher.i: Controller/Searcher/CubeSearcher.cpp.i

.PHONY : Controller/Searcher/CubeSearcher.i

# target to preprocess a source file
Controller/Searcher/CubeSearcher.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/CubeSearcher.cpp.i
.PHONY : Controller/Searcher/CubeSearcher.cpp.i

Controller/Searcher/CubeSearcher.s: Controller/Searcher/CubeSearcher.cpp.s

.PHONY : Controller/Searcher/CubeSearcher.s

# target to generate assembly for a file
Controller/Searcher/CubeSearcher.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/CubeSearcher.cpp.s
.PHONY : Controller/Searcher/CubeSearcher.cpp.s

Controller/Searcher/IDACubeSearcher.o: Controller/Searcher/IDACubeSearcher.cpp.o

.PHONY : Controller/Searcher/IDACubeSearcher.o

# target to build an object file
Controller/Searcher/IDACubeSearcher.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/IDACubeSearcher.cpp.o
.PHONY : Controller/Searcher/IDACubeSearcher.cpp.o

Controller/Searcher/IDACubeSearcher.i: Controller/Searcher/IDACubeSearcher.cpp.i

.PHONY : Controller/Searcher/IDACubeSearcher.i

# target to preprocess a source file
Controller/Searcher/IDACubeSearcher.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/IDACubeSearcher.cpp.i
.PHONY : Controller/Searcher/IDACubeSearcher.cpp.i

Controller/Searcher/IDACubeSearcher.s: Controller/Searcher/IDACubeSearcher.cpp.s

.PHONY : Controller/Searcher/IDACubeSearcher.s

# target to generate assembly for a file
Controller/Searcher/IDACubeSearcher.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/IDACubeSearcher.cpp.s
.PHONY : Controller/Searcher/IDACubeSearcher.cpp.s

Controller/Searcher/MovePruner.o: Controller/Searcher/MovePruner.cpp.o

.PHONY : Controller/Searcher/MovePruner.o

# target to build an object file
Controller/Searcher/MovePruner.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/MovePruner.cpp.o
.PHONY : Controller/Searcher/MovePruner.cpp.o

Controller/Searcher/MovePruner.i: Controller/Searcher/MovePruner.cpp.i

.PHONY : Controller/Searcher/MovePruner.i

# target to preprocess a source file
Controller/Searcher/MovePruner.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/MovePruner.cpp.i
.PHONY : Controller/Searcher/MovePruner.cpp.i

Controller/Searcher/MovePruner.s: Controller/Searcher/MovePruner.cpp.s

.PHONY : Controller/Searcher/MovePruner.s

# target to generate assembly for a file
Controller/Searcher/MovePruner.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/MovePruner.cpp.s
.PHONY : Controller/Searcher/MovePruner.cpp.s

Controller/Searcher/PatternDatabaseIndexer.o: Controller/Searcher/PatternDatabaseIndexer.cpp.o

.PHONY : Controller/Searcher/PatternDatabaseIndexer.o

# target to build an object file
Controller/Searcher/PatternDatabaseIndexer.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/PatternDatabaseIndexer.cpp.o
.PHONY : Controller/Searcher/PatternDatabaseIndexer.cpp.o

Controller/Searcher/PatternDatabaseIndexer.i: Controller/Searcher/PatternDatabaseIndexer.cpp.i

.PHONY : Controller/Searcher/PatternDatabaseIndexer.i

# target to preprocess a source file
Controller/Searcher/PatternDatabaseIndexer.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/PatternDatabaseIndexer.cpp.i
.PHONY : Controller/Searcher/PatternDatabaseIndexer.cpp.i

Controller/Searcher/PatternDatabaseIndexer.s: Controller/Searcher/PatternDatabaseIndexer.cpp.s

.PHONY : Controller/Searcher/PatternDatabaseIndexer.s

# target to generate assembly for a file
Controller/Searcher/PatternDatabaseIndexer.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Controller/Searcher/PatternDatabaseIndexer.cpp.s
.PHONY : Controller/Searcher/PatternDatabaseIndexer.cpp.s

KorfCubeSolver.o: KorfCubeSolver.cpp.o

.PHONY : KorfCubeSolver.o

# target to build an object file
KorfCubeSolver.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/KorfCubeSolver.cpp.o
.PHONY : KorfCubeSolver.cpp.o

KorfCubeSolver.i: KorfCubeSolver.cpp.i

.PHONY : KorfCubeSolver.i

# target to preprocess a source file
KorfCubeSolver.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/KorfCubeSolver.cpp.i
.PHONY : KorfCubeSolver.cpp.i

KorfCubeSolver.s: KorfCubeSolver.cpp.s

.PHONY : KorfCubeSolver.s

# target to generate assembly for a file
KorfCubeSolver.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/KorfCubeSolver.cpp.s
.PHONY : KorfCubeSolver.cpp.s

Model/Goal/DatabaseGoal.o: Model/Goal/DatabaseGoal.cpp.o

.PHONY : Model/Goal/DatabaseGoal.o

# target to build an object file
Model/Goal/DatabaseGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/DatabaseGoal.cpp.o
.PHONY : Model/Goal/DatabaseGoal.cpp.o

Model/Goal/DatabaseGoal.i: Model/Goal/DatabaseGoal.cpp.i

.PHONY : Model/Goal/DatabaseGoal.i

# target to preprocess a source file
Model/Goal/DatabaseGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/DatabaseGoal.cpp.i
.PHONY : Model/Goal/DatabaseGoal.cpp.i

Model/Goal/DatabaseGoal.s: Model/Goal/DatabaseGoal.cpp.s

.PHONY : Model/Goal/DatabaseGoal.s

# target to generate assembly for a file
Model/Goal/DatabaseGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/DatabaseGoal.cpp.s
.PHONY : Model/Goal/DatabaseGoal.cpp.s

Model/Goal/Goal.o: Model/Goal/Goal.cpp.o

.PHONY : Model/Goal/Goal.o

# target to build an object file
Model/Goal/Goal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Goal.cpp.o
.PHONY : Model/Goal/Goal.cpp.o

Model/Goal/Goal.i: Model/Goal/Goal.cpp.i

.PHONY : Model/Goal/Goal.i

# target to preprocess a source file
Model/Goal/Goal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Goal.cpp.i
.PHONY : Model/Goal/Goal.cpp.i

Model/Goal/Goal.s: Model/Goal/Goal.cpp.s

.PHONY : Model/Goal/Goal.s

# target to generate assembly for a file
Model/Goal/Goal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Goal.cpp.s
.PHONY : Model/Goal/Goal.cpp.s

Model/Goal/Korf/CornerDatabaseGoal.o: Model/Goal/Korf/CornerDatabaseGoal.cpp.o

.PHONY : Model/Goal/Korf/CornerDatabaseGoal.o

# target to build an object file
Model/Goal/Korf/CornerDatabaseGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/CornerDatabaseGoal.cpp.o
.PHONY : Model/Goal/Korf/CornerDatabaseGoal.cpp.o

Model/Goal/Korf/CornerDatabaseGoal.i: Model/Goal/Korf/CornerDatabaseGoal.cpp.i

.PHONY : Model/Goal/Korf/CornerDatabaseGoal.i

# target to preprocess a source file
Model/Goal/Korf/CornerDatabaseGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/CornerDatabaseGoal.cpp.i
.PHONY : Model/Goal/Korf/CornerDatabaseGoal.cpp.i

Model/Goal/Korf/CornerDatabaseGoal.s: Model/Goal/Korf/CornerDatabaseGoal.cpp.s

.PHONY : Model/Goal/Korf/CornerDatabaseGoal.s

# target to generate assembly for a file
Model/Goal/Korf/CornerDatabaseGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/CornerDatabaseGoal.cpp.s
.PHONY : Model/Goal/Korf/CornerDatabaseGoal.cpp.s

Model/Goal/Korf/EdgeDatabaseGoal.o: Model/Goal/Korf/EdgeDatabaseGoal.cpp.o

.PHONY : Model/Goal/Korf/EdgeDatabaseGoal.o

# target to build an object file
Model/Goal/Korf/EdgeDatabaseGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/EdgeDatabaseGoal.cpp.o
.PHONY : Model/Goal/Korf/EdgeDatabaseGoal.cpp.o

Model/Goal/Korf/EdgeDatabaseGoal.i: Model/Goal/Korf/EdgeDatabaseGoal.cpp.i

.PHONY : Model/Goal/Korf/EdgeDatabaseGoal.i

# target to preprocess a source file
Model/Goal/Korf/EdgeDatabaseGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/EdgeDatabaseGoal.cpp.i
.PHONY : Model/Goal/Korf/EdgeDatabaseGoal.cpp.i

Model/Goal/Korf/EdgeDatabaseGoal.s: Model/Goal/Korf/EdgeDatabaseGoal.cpp.s

.PHONY : Model/Goal/Korf/EdgeDatabaseGoal.s

# target to generate assembly for a file
Model/Goal/Korf/EdgeDatabaseGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/EdgeDatabaseGoal.cpp.s
.PHONY : Model/Goal/Korf/EdgeDatabaseGoal.cpp.s

Model/Goal/Korf/EdgePermutationDatabaseGoal.o: Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.o

.PHONY : Model/Goal/Korf/EdgePermutationDatabaseGoal.o

# target to build an object file
Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.o
.PHONY : Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.o

Model/Goal/Korf/EdgePermutationDatabaseGoal.i: Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.i

.PHONY : Model/Goal/Korf/EdgePermutationDatabaseGoal.i

# target to preprocess a source file
Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.i
.PHONY : Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.i

Model/Goal/Korf/EdgePermutationDatabaseGoal.s: Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.s

.PHONY : Model/Goal/Korf/EdgePermutationDatabaseGoal.s

# target to generate assembly for a file
Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.s
.PHONY : Model/Goal/Korf/EdgePermutationDatabaseGoal.cpp.s

Model/Goal/OrientGoal.o: Model/Goal/OrientGoal.cpp.o

.PHONY : Model/Goal/OrientGoal.o

# target to build an object file
Model/Goal/OrientGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/OrientGoal.cpp.o
.PHONY : Model/Goal/OrientGoal.cpp.o

Model/Goal/OrientGoal.i: Model/Goal/OrientGoal.cpp.i

.PHONY : Model/Goal/OrientGoal.i

# target to preprocess a source file
Model/Goal/OrientGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/OrientGoal.cpp.i
.PHONY : Model/Goal/OrientGoal.cpp.i

Model/Goal/OrientGoal.s: Model/Goal/OrientGoal.cpp.s

.PHONY : Model/Goal/OrientGoal.s

# target to generate assembly for a file
Model/Goal/OrientGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/OrientGoal.cpp.s
.PHONY : Model/Goal/OrientGoal.cpp.s

Model/Goal/SolveGoal.o: Model/Goal/SolveGoal.cpp.o

.PHONY : Model/Goal/SolveGoal.o

# target to build an object file
Model/Goal/SolveGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/SolveGoal.cpp.o
.PHONY : Model/Goal/SolveGoal.cpp.o

Model/Goal/SolveGoal.i: Model/Goal/SolveGoal.cpp.i

.PHONY : Model/Goal/SolveGoal.i

# target to preprocess a source file
Model/Goal/SolveGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/SolveGoal.cpp.i
.PHONY : Model/Goal/SolveGoal.cpp.i

Model/Goal/SolveGoal.s: Model/Goal/SolveGoal.cpp.s

.PHONY : Model/Goal/SolveGoal.s

# target to generate assembly for a file
Model/Goal/SolveGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/SolveGoal.cpp.s
.PHONY : Model/Goal/SolveGoal.cpp.s

Model/Goal/TestGoal.o: Model/Goal/TestGoal.cpp.o

.PHONY : Model/Goal/TestGoal.o

# target to build an object file
Model/Goal/TestGoal.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/TestGoal.cpp.o
.PHONY : Model/Goal/TestGoal.cpp.o

Model/Goal/TestGoal.i: Model/Goal/TestGoal.cpp.i

.PHONY : Model/Goal/TestGoal.i

# target to preprocess a source file
Model/Goal/TestGoal.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/TestGoal.cpp.i
.PHONY : Model/Goal/TestGoal.cpp.i

Model/Goal/TestGoal.s: Model/Goal/TestGoal.cpp.s

.PHONY : Model/Goal/TestGoal.s

# target to generate assembly for a file
Model/Goal/TestGoal.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/TestGoal.cpp.s
.PHONY : Model/Goal/TestGoal.cpp.s

Model/Goal/Thistlethwaite/GoalG0_G1.o: Model/Goal/Thistlethwaite/GoalG0_G1.cpp.o

.PHONY : Model/Goal/Thistlethwaite/GoalG0_G1.o

# target to build an object file
Model/Goal/Thistlethwaite/GoalG0_G1.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG0_G1.cpp.o
.PHONY : Model/Goal/Thistlethwaite/GoalG0_G1.cpp.o

Model/Goal/Thistlethwaite/GoalG0_G1.i: Model/Goal/Thistlethwaite/GoalG0_G1.cpp.i

.PHONY : Model/Goal/Thistlethwaite/GoalG0_G1.i

# target to preprocess a source file
Model/Goal/Thistlethwaite/GoalG0_G1.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG0_G1.cpp.i
.PHONY : Model/Goal/Thistlethwaite/GoalG0_G1.cpp.i

Model/Goal/Thistlethwaite/GoalG0_G1.s: Model/Goal/Thistlethwaite/GoalG0_G1.cpp.s

.PHONY : Model/Goal/Thistlethwaite/GoalG0_G1.s

# target to generate assembly for a file
Model/Goal/Thistlethwaite/GoalG0_G1.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG0_G1.cpp.s
.PHONY : Model/Goal/Thistlethwaite/GoalG0_G1.cpp.s

Model/Goal/Thistlethwaite/GoalG1_G2.o: Model/Goal/Thistlethwaite/GoalG1_G2.cpp.o

.PHONY : Model/Goal/Thistlethwaite/GoalG1_G2.o

# target to build an object file
Model/Goal/Thistlethwaite/GoalG1_G2.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG1_G2.cpp.o
.PHONY : Model/Goal/Thistlethwaite/GoalG1_G2.cpp.o

Model/Goal/Thistlethwaite/GoalG1_G2.i: Model/Goal/Thistlethwaite/GoalG1_G2.cpp.i

.PHONY : Model/Goal/Thistlethwaite/GoalG1_G2.i

# target to preprocess a source file
Model/Goal/Thistlethwaite/GoalG1_G2.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG1_G2.cpp.i
.PHONY : Model/Goal/Thistlethwaite/GoalG1_G2.cpp.i

Model/Goal/Thistlethwaite/GoalG1_G2.s: Model/Goal/Thistlethwaite/GoalG1_G2.cpp.s

.PHONY : Model/Goal/Thistlethwaite/GoalG1_G2.s

# target to generate assembly for a file
Model/Goal/Thistlethwaite/GoalG1_G2.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG1_G2.cpp.s
.PHONY : Model/Goal/Thistlethwaite/GoalG1_G2.cpp.s

Model/Goal/Thistlethwaite/GoalG2_G3_Corners.o: Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.o

.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Corners.o

# target to build an object file
Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.o
.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.o

Model/Goal/Thistlethwaite/GoalG2_G3_Corners.i: Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.i

.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Corners.i

# target to preprocess a source file
Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.i
.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.i

Model/Goal/Thistlethwaite/GoalG2_G3_Corners.s: Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.s

.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Corners.s

# target to generate assembly for a file
Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.s
.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Corners.cpp.s

Model/Goal/Thistlethwaite/GoalG2_G3_Edges.o: Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.o

.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Edges.o

# target to build an object file
Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.o
.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.o

Model/Goal/Thistlethwaite/GoalG2_G3_Edges.i: Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.i

.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Edges.i

# target to preprocess a source file
Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.i
.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.i

Model/Goal/Thistlethwaite/GoalG2_G3_Edges.s: Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.s

.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Edges.s

# target to generate assembly for a file
Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.s
.PHONY : Model/Goal/Thistlethwaite/GoalG2_G3_Edges.cpp.s

Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.o: Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.o

.PHONY : Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.o

# target to build an object file
Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.o
.PHONY : Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.o

Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.i: Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.i

.PHONY : Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.i

# target to preprocess a source file
Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.i
.PHONY : Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.i

Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.s: Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.s

.PHONY : Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.s

# target to generate assembly for a file
Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.s
.PHONY : Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.cpp.s

Model/MoveStore/G1TwistStore.o: Model/MoveStore/G1TwistStore.cpp.o

.PHONY : Model/MoveStore/G1TwistStore.o

# target to build an object file
Model/MoveStore/G1TwistStore.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G1TwistStore.cpp.o
.PHONY : Model/MoveStore/G1TwistStore.cpp.o

Model/MoveStore/G1TwistStore.i: Model/MoveStore/G1TwistStore.cpp.i

.PHONY : Model/MoveStore/G1TwistStore.i

# target to preprocess a source file
Model/MoveStore/G1TwistStore.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G1TwistStore.cpp.i
.PHONY : Model/MoveStore/G1TwistStore.cpp.i

Model/MoveStore/G1TwistStore.s: Model/MoveStore/G1TwistStore.cpp.s

.PHONY : Model/MoveStore/G1TwistStore.s

# target to generate assembly for a file
Model/MoveStore/G1TwistStore.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G1TwistStore.cpp.s
.PHONY : Model/MoveStore/G1TwistStore.cpp.s

Model/MoveStore/G2TwistStore.o: Model/MoveStore/G2TwistStore.cpp.o

.PHONY : Model/MoveStore/G2TwistStore.o

# target to build an object file
Model/MoveStore/G2TwistStore.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G2TwistStore.cpp.o
.PHONY : Model/MoveStore/G2TwistStore.cpp.o

Model/MoveStore/G2TwistStore.i: Model/MoveStore/G2TwistStore.cpp.i

.PHONY : Model/MoveStore/G2TwistStore.i

# target to preprocess a source file
Model/MoveStore/G2TwistStore.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G2TwistStore.cpp.i
.PHONY : Model/MoveStore/G2TwistStore.cpp.i

Model/MoveStore/G2TwistStore.s: Model/MoveStore/G2TwistStore.cpp.s

.PHONY : Model/MoveStore/G2TwistStore.s

# target to generate assembly for a file
Model/MoveStore/G2TwistStore.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G2TwistStore.cpp.s
.PHONY : Model/MoveStore/G2TwistStore.cpp.s

Model/MoveStore/G3TwistStore.o: Model/MoveStore/G3TwistStore.cpp.o

.PHONY : Model/MoveStore/G3TwistStore.o

# target to build an object file
Model/MoveStore/G3TwistStore.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G3TwistStore.cpp.o
.PHONY : Model/MoveStore/G3TwistStore.cpp.o

Model/MoveStore/G3TwistStore.i: Model/MoveStore/G3TwistStore.cpp.i

.PHONY : Model/MoveStore/G3TwistStore.i

# target to preprocess a source file
Model/MoveStore/G3TwistStore.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G3TwistStore.cpp.i
.PHONY : Model/MoveStore/G3TwistStore.cpp.i

Model/MoveStore/G3TwistStore.s: Model/MoveStore/G3TwistStore.cpp.s

.PHONY : Model/MoveStore/G3TwistStore.s

# target to generate assembly for a file
Model/MoveStore/G3TwistStore.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/G3TwistStore.cpp.s
.PHONY : Model/MoveStore/G3TwistStore.cpp.s

Model/MoveStore/MoveStore.o: Model/MoveStore/MoveStore.cpp.o

.PHONY : Model/MoveStore/MoveStore.o

# target to build an object file
Model/MoveStore/MoveStore.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/MoveStore.cpp.o
.PHONY : Model/MoveStore/MoveStore.cpp.o

Model/MoveStore/MoveStore.i: Model/MoveStore/MoveStore.cpp.i

.PHONY : Model/MoveStore/MoveStore.i

# target to preprocess a source file
Model/MoveStore/MoveStore.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/MoveStore.cpp.i
.PHONY : Model/MoveStore/MoveStore.cpp.i

Model/MoveStore/MoveStore.s: Model/MoveStore/MoveStore.cpp.s

.PHONY : Model/MoveStore/MoveStore.s

# target to generate assembly for a file
Model/MoveStore/MoveStore.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/MoveStore.cpp.s
.PHONY : Model/MoveStore/MoveStore.cpp.s

Model/MoveStore/RotationStore.o: Model/MoveStore/RotationStore.cpp.o

.PHONY : Model/MoveStore/RotationStore.o

# target to build an object file
Model/MoveStore/RotationStore.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/RotationStore.cpp.o
.PHONY : Model/MoveStore/RotationStore.cpp.o

Model/MoveStore/RotationStore.i: Model/MoveStore/RotationStore.cpp.i

.PHONY : Model/MoveStore/RotationStore.i

# target to preprocess a source file
Model/MoveStore/RotationStore.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/RotationStore.cpp.i
.PHONY : Model/MoveStore/RotationStore.cpp.i

Model/MoveStore/RotationStore.s: Model/MoveStore/RotationStore.cpp.s

.PHONY : Model/MoveStore/RotationStore.s

# target to generate assembly for a file
Model/MoveStore/RotationStore.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/RotationStore.cpp.s
.PHONY : Model/MoveStore/RotationStore.cpp.s

Model/MoveStore/TwistStore.o: Model/MoveStore/TwistStore.cpp.o

.PHONY : Model/MoveStore/TwistStore.o

# target to build an object file
Model/MoveStore/TwistStore.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/TwistStore.cpp.o
.PHONY : Model/MoveStore/TwistStore.cpp.o

Model/MoveStore/TwistStore.i: Model/MoveStore/TwistStore.cpp.i

.PHONY : Model/MoveStore/TwistStore.i

# target to preprocess a source file
Model/MoveStore/TwistStore.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/TwistStore.cpp.i
.PHONY : Model/MoveStore/TwistStore.cpp.i

Model/MoveStore/TwistStore.s: Model/MoveStore/TwistStore.cpp.s

.PHONY : Model/MoveStore/TwistStore.s

# target to generate assembly for a file
Model/MoveStore/TwistStore.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/MoveStore/TwistStore.cpp.s
.PHONY : Model/MoveStore/TwistStore.cpp.s

Model/PatternDatabase/Korf/CornerPatternDatabase.o: Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/Korf/CornerPatternDatabase.o

# target to build an object file
Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.o

Model/PatternDatabase/Korf/CornerPatternDatabase.i: Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/Korf/CornerPatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.i

Model/PatternDatabase/Korf/CornerPatternDatabase.s: Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/Korf/CornerPatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/Korf/CornerPatternDatabase.cpp.s

Model/PatternDatabase/Korf/EdgeG1PatternDatabase.o: Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/Korf/EdgeG1PatternDatabase.o

# target to build an object file
Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.o

Model/PatternDatabase/Korf/EdgeG1PatternDatabase.i: Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/Korf/EdgeG1PatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.i

Model/PatternDatabase/Korf/EdgeG1PatternDatabase.s: Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/Korf/EdgeG1PatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/Korf/EdgeG1PatternDatabase.cpp.s

Model/PatternDatabase/Korf/EdgeG2PatternDatabase.o: Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/Korf/EdgeG2PatternDatabase.o

# target to build an object file
Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.o

Model/PatternDatabase/Korf/EdgeG2PatternDatabase.i: Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/Korf/EdgeG2PatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.i

Model/PatternDatabase/Korf/EdgeG2PatternDatabase.s: Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/Korf/EdgeG2PatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/Korf/EdgeG2PatternDatabase.cpp.s

Model/PatternDatabase/Korf/EdgePatternDatabase.o: Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/Korf/EdgePatternDatabase.o

# target to build an object file
Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.o

Model/PatternDatabase/Korf/EdgePatternDatabase.i: Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/Korf/EdgePatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.i

Model/PatternDatabase/Korf/EdgePatternDatabase.s: Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/Korf/EdgePatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/Korf/EdgePatternDatabase.cpp.s

Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.o: Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.o

# target to build an object file
Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.o

Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.i: Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.i

Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.s: Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.cpp.s

Model/PatternDatabase/Korf/KorfPatternDatabase.o: Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/Korf/KorfPatternDatabase.o

# target to build an object file
Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.o

Model/PatternDatabase/Korf/KorfPatternDatabase.i: Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/Korf/KorfPatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.i

Model/PatternDatabase/Korf/KorfPatternDatabase.s: Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/Korf/KorfPatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/Korf/KorfPatternDatabase.cpp.s

Model/PatternDatabase/PatternDatabase.o: Model/PatternDatabase/PatternDatabase.cpp.o

.PHONY : Model/PatternDatabase/PatternDatabase.o

# target to build an object file
Model/PatternDatabase/PatternDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/PatternDatabase.cpp.o
.PHONY : Model/PatternDatabase/PatternDatabase.cpp.o

Model/PatternDatabase/PatternDatabase.i: Model/PatternDatabase/PatternDatabase.cpp.i

.PHONY : Model/PatternDatabase/PatternDatabase.i

# target to preprocess a source file
Model/PatternDatabase/PatternDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/PatternDatabase.cpp.i
.PHONY : Model/PatternDatabase/PatternDatabase.cpp.i

Model/PatternDatabase/PatternDatabase.s: Model/PatternDatabase/PatternDatabase.cpp.s

.PHONY : Model/PatternDatabase/PatternDatabase.s

# target to generate assembly for a file
Model/PatternDatabase/PatternDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/PatternDatabase/PatternDatabase.cpp.s
.PHONY : Model/PatternDatabase/PatternDatabase.cpp.s

Model/RubiksCube.o: Model/RubiksCube.cpp.o

.PHONY : Model/RubiksCube.o

# target to build an object file
Model/RubiksCube.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCube.cpp.o
.PHONY : Model/RubiksCube.cpp.o

Model/RubiksCube.i: Model/RubiksCube.cpp.i

.PHONY : Model/RubiksCube.i

# target to preprocess a source file
Model/RubiksCube.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCube.cpp.i
.PHONY : Model/RubiksCube.cpp.i

Model/RubiksCube.s: Model/RubiksCube.cpp.s

.PHONY : Model/RubiksCube.s

# target to generate assembly for a file
Model/RubiksCube.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCube.cpp.s
.PHONY : Model/RubiksCube.cpp.s

Model/RubiksCubeIndexModel.o: Model/RubiksCubeIndexModel.cpp.o

.PHONY : Model/RubiksCubeIndexModel.o

# target to build an object file
Model/RubiksCubeIndexModel.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCubeIndexModel.cpp.o
.PHONY : Model/RubiksCubeIndexModel.cpp.o

Model/RubiksCubeIndexModel.i: Model/RubiksCubeIndexModel.cpp.i

.PHONY : Model/RubiksCubeIndexModel.i

# target to preprocess a source file
Model/RubiksCubeIndexModel.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCubeIndexModel.cpp.i
.PHONY : Model/RubiksCubeIndexModel.cpp.i

Model/RubiksCubeIndexModel.s: Model/RubiksCubeIndexModel.cpp.s

.PHONY : Model/RubiksCubeIndexModel.s

# target to generate assembly for a file
Model/RubiksCubeIndexModel.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCubeIndexModel.cpp.s
.PHONY : Model/RubiksCubeIndexModel.cpp.s

Model/RubiksCubeModel.o: Model/RubiksCubeModel.cpp.o

.PHONY : Model/RubiksCubeModel.o

# target to build an object file
Model/RubiksCubeModel.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCubeModel.cpp.o
.PHONY : Model/RubiksCubeModel.cpp.o

Model/RubiksCubeModel.i: Model/RubiksCubeModel.cpp.i

.PHONY : Model/RubiksCubeModel.i

# target to preprocess a source file
Model/RubiksCubeModel.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCubeModel.cpp.i
.PHONY : Model/RubiksCubeModel.cpp.i

Model/RubiksCubeModel.s: Model/RubiksCubeModel.cpp.s

.PHONY : Model/RubiksCubeModel.s

# target to generate assembly for a file
Model/RubiksCubeModel.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Model/RubiksCubeModel.cpp.s
.PHONY : Model/RubiksCubeModel.cpp.s

Util/AutoTimer.o: Util/AutoTimer.cpp.o

.PHONY : Util/AutoTimer.o

# target to build an object file
Util/AutoTimer.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/AutoTimer.cpp.o
.PHONY : Util/AutoTimer.cpp.o

Util/AutoTimer.i: Util/AutoTimer.cpp.i

.PHONY : Util/AutoTimer.i

# target to preprocess a source file
Util/AutoTimer.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/AutoTimer.cpp.i
.PHONY : Util/AutoTimer.cpp.i

Util/AutoTimer.s: Util/AutoTimer.cpp.s

.PHONY : Util/AutoTimer.s

# target to generate assembly for a file
Util/AutoTimer.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/AutoTimer.cpp.s
.PHONY : Util/AutoTimer.cpp.s

Util/NibbleArray.o: Util/NibbleArray.cpp.o

.PHONY : Util/NibbleArray.o

# target to build an object file
Util/NibbleArray.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/NibbleArray.cpp.o
.PHONY : Util/NibbleArray.cpp.o

Util/NibbleArray.i: Util/NibbleArray.cpp.i

.PHONY : Util/NibbleArray.i

# target to preprocess a source file
Util/NibbleArray.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/NibbleArray.cpp.i
.PHONY : Util/NibbleArray.cpp.i

Util/NibbleArray.s: Util/NibbleArray.cpp.s

.PHONY : Util/NibbleArray.s

# target to generate assembly for a file
Util/NibbleArray.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/NibbleArray.cpp.s
.PHONY : Util/NibbleArray.cpp.s

Util/Random.o: Util/Random.cpp.o

.PHONY : Util/Random.o

# target to build an object file
Util/Random.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/Random.cpp.o
.PHONY : Util/Random.cpp.o

Util/Random.i: Util/Random.cpp.i

.PHONY : Util/Random.i

# target to preprocess a source file
Util/Random.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/Random.cpp.i
.PHONY : Util/Random.cpp.i

Util/Random.s: Util/Random.cpp.s

.PHONY : Util/Random.s

# target to generate assembly for a file
Util/Random.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/Random.cpp.s
.PHONY : Util/Random.cpp.s

Util/RubiksCubeException.o: Util/RubiksCubeException.cpp.o

.PHONY : Util/RubiksCubeException.o

# target to build an object file
Util/RubiksCubeException.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/RubiksCubeException.cpp.o
.PHONY : Util/RubiksCubeException.cpp.o

Util/RubiksCubeException.i: Util/RubiksCubeException.cpp.i

.PHONY : Util/RubiksCubeException.i

# target to preprocess a source file
Util/RubiksCubeException.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/RubiksCubeException.cpp.i
.PHONY : Util/RubiksCubeException.cpp.i

Util/RubiksCubeException.s: Util/RubiksCubeException.cpp.s

.PHONY : Util/RubiksCubeException.s

# target to generate assembly for a file
Util/RubiksCubeException.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/RubiksCubeException.cpp.s
.PHONY : Util/RubiksCubeException.cpp.s

Util/Timer.o: Util/Timer.cpp.o

.PHONY : Util/Timer.o

# target to build an object file
Util/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/Timer.cpp.o
.PHONY : Util/Timer.cpp.o

Util/Timer.i: Util/Timer.cpp.i

.PHONY : Util/Timer.i

# target to preprocess a source file
Util/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/Timer.cpp.i
.PHONY : Util/Timer.cpp.i

Util/Timer.s: Util/Timer.cpp.s

.PHONY : Util/Timer.s

# target to generate assembly for a file
Util/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/Util/Timer.cpp.s
.PHONY : Util/Timer.cpp.s

rubiksCube.o: rubiksCube.cpp.o

.PHONY : rubiksCube.o

# target to build an object file
rubiksCube.cpp.o:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/rubiksCube.cpp.o
.PHONY : rubiksCube.cpp.o

rubiksCube.i: rubiksCube.cpp.i

.PHONY : rubiksCube.i

# target to preprocess a source file
rubiksCube.cpp.i:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/rubiksCube.cpp.i
.PHONY : rubiksCube.cpp.i

rubiksCube.s: rubiksCube.cpp.s

.PHONY : rubiksCube.s

# target to generate assembly for a file
rubiksCube.cpp.s:
	$(MAKE) -f CMakeFiles/rubiksCube.dir/build.make CMakeFiles/rubiksCube.dir/rubiksCube.cpp.s
.PHONY : rubiksCube.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... rubiksCube"
	@echo "... edit_cache"
	@echo "... Controller/Searcher/CubeSearcher.o"
	@echo "... Controller/Searcher/CubeSearcher.i"
	@echo "... Controller/Searcher/CubeSearcher.s"
	@echo "... Controller/Searcher/IDACubeSearcher.o"
	@echo "... Controller/Searcher/IDACubeSearcher.i"
	@echo "... Controller/Searcher/IDACubeSearcher.s"
	@echo "... Controller/Searcher/MovePruner.o"
	@echo "... Controller/Searcher/MovePruner.i"
	@echo "... Controller/Searcher/MovePruner.s"
	@echo "... Controller/Searcher/PatternDatabaseIndexer.o"
	@echo "... Controller/Searcher/PatternDatabaseIndexer.i"
	@echo "... Controller/Searcher/PatternDatabaseIndexer.s"
	@echo "... KorfCubeSolver.o"
	@echo "... KorfCubeSolver.i"
	@echo "... KorfCubeSolver.s"
	@echo "... Model/Goal/DatabaseGoal.o"
	@echo "... Model/Goal/DatabaseGoal.i"
	@echo "... Model/Goal/DatabaseGoal.s"
	@echo "... Model/Goal/Goal.o"
	@echo "... Model/Goal/Goal.i"
	@echo "... Model/Goal/Goal.s"
	@echo "... Model/Goal/Korf/CornerDatabaseGoal.o"
	@echo "... Model/Goal/Korf/CornerDatabaseGoal.i"
	@echo "... Model/Goal/Korf/CornerDatabaseGoal.s"
	@echo "... Model/Goal/Korf/EdgeDatabaseGoal.o"
	@echo "... Model/Goal/Korf/EdgeDatabaseGoal.i"
	@echo "... Model/Goal/Korf/EdgeDatabaseGoal.s"
	@echo "... Model/Goal/Korf/EdgePermutationDatabaseGoal.o"
	@echo "... Model/Goal/Korf/EdgePermutationDatabaseGoal.i"
	@echo "... Model/Goal/Korf/EdgePermutationDatabaseGoal.s"
	@echo "... Model/Goal/OrientGoal.o"
	@echo "... Model/Goal/OrientGoal.i"
	@echo "... Model/Goal/OrientGoal.s"
	@echo "... Model/Goal/SolveGoal.o"
	@echo "... Model/Goal/SolveGoal.i"
	@echo "... Model/Goal/SolveGoal.s"
	@echo "... Model/Goal/TestGoal.o"
	@echo "... Model/Goal/TestGoal.i"
	@echo "... Model/Goal/TestGoal.s"
	@echo "... Model/Goal/Thistlethwaite/GoalG0_G1.o"
	@echo "... Model/Goal/Thistlethwaite/GoalG0_G1.i"
	@echo "... Model/Goal/Thistlethwaite/GoalG0_G1.s"
	@echo "... Model/Goal/Thistlethwaite/GoalG1_G2.o"
	@echo "... Model/Goal/Thistlethwaite/GoalG1_G2.i"
	@echo "... Model/Goal/Thistlethwaite/GoalG1_G2.s"
	@echo "... Model/Goal/Thistlethwaite/GoalG2_G3_Corners.o"
	@echo "... Model/Goal/Thistlethwaite/GoalG2_G3_Corners.i"
	@echo "... Model/Goal/Thistlethwaite/GoalG2_G3_Corners.s"
	@echo "... Model/Goal/Thistlethwaite/GoalG2_G3_Edges.o"
	@echo "... Model/Goal/Thistlethwaite/GoalG2_G3_Edges.i"
	@echo "... Model/Goal/Thistlethwaite/GoalG2_G3_Edges.s"
	@echo "... Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.o"
	@echo "... Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.i"
	@echo "... Model/Goal/Thistlethwaite/GoalG3_Permute_Corners.s"
	@echo "... Model/MoveStore/G1TwistStore.o"
	@echo "... Model/MoveStore/G1TwistStore.i"
	@echo "... Model/MoveStore/G1TwistStore.s"
	@echo "... Model/MoveStore/G2TwistStore.o"
	@echo "... Model/MoveStore/G2TwistStore.i"
	@echo "... Model/MoveStore/G2TwistStore.s"
	@echo "... Model/MoveStore/G3TwistStore.o"
	@echo "... Model/MoveStore/G3TwistStore.i"
	@echo "... Model/MoveStore/G3TwistStore.s"
	@echo "... Model/MoveStore/MoveStore.o"
	@echo "... Model/MoveStore/MoveStore.i"
	@echo "... Model/MoveStore/MoveStore.s"
	@echo "... Model/MoveStore/RotationStore.o"
	@echo "... Model/MoveStore/RotationStore.i"
	@echo "... Model/MoveStore/RotationStore.s"
	@echo "... Model/MoveStore/TwistStore.o"
	@echo "... Model/MoveStore/TwistStore.i"
	@echo "... Model/MoveStore/TwistStore.s"
	@echo "... Model/PatternDatabase/Korf/CornerPatternDatabase.o"
	@echo "... Model/PatternDatabase/Korf/CornerPatternDatabase.i"
	@echo "... Model/PatternDatabase/Korf/CornerPatternDatabase.s"
	@echo "... Model/PatternDatabase/Korf/EdgeG1PatternDatabase.o"
	@echo "... Model/PatternDatabase/Korf/EdgeG1PatternDatabase.i"
	@echo "... Model/PatternDatabase/Korf/EdgeG1PatternDatabase.s"
	@echo "... Model/PatternDatabase/Korf/EdgeG2PatternDatabase.o"
	@echo "... Model/PatternDatabase/Korf/EdgeG2PatternDatabase.i"
	@echo "... Model/PatternDatabase/Korf/EdgeG2PatternDatabase.s"
	@echo "... Model/PatternDatabase/Korf/EdgePatternDatabase.o"
	@echo "... Model/PatternDatabase/Korf/EdgePatternDatabase.i"
	@echo "... Model/PatternDatabase/Korf/EdgePatternDatabase.s"
	@echo "... Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.o"
	@echo "... Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.i"
	@echo "... Model/PatternDatabase/Korf/EdgePermutationPatternDatabase.s"
	@echo "... Model/PatternDatabase/Korf/KorfPatternDatabase.o"
	@echo "... Model/PatternDatabase/Korf/KorfPatternDatabase.i"
	@echo "... Model/PatternDatabase/Korf/KorfPatternDatabase.s"
	@echo "... Model/PatternDatabase/PatternDatabase.o"
	@echo "... Model/PatternDatabase/PatternDatabase.i"
	@echo "... Model/PatternDatabase/PatternDatabase.s"
	@echo "... Model/RubiksCube.o"
	@echo "... Model/RubiksCube.i"
	@echo "... Model/RubiksCube.s"
	@echo "... Model/RubiksCubeIndexModel.o"
	@echo "... Model/RubiksCubeIndexModel.i"
	@echo "... Model/RubiksCubeIndexModel.s"
	@echo "... Model/RubiksCubeModel.o"
	@echo "... Model/RubiksCubeModel.i"
	@echo "... Model/RubiksCubeModel.s"
	@echo "... Util/AutoTimer.o"
	@echo "... Util/AutoTimer.i"
	@echo "... Util/AutoTimer.s"
	@echo "... Util/NibbleArray.o"
	@echo "... Util/NibbleArray.i"
	@echo "... Util/NibbleArray.s"
	@echo "... Util/Random.o"
	@echo "... Util/Random.i"
	@echo "... Util/Random.s"
	@echo "... Util/RubiksCubeException.o"
	@echo "... Util/RubiksCubeException.i"
	@echo "... Util/RubiksCubeException.s"
	@echo "... Util/Timer.o"
	@echo "... Util/Timer.i"
	@echo "... Util/Timer.s"
	@echo "... rubiksCube.o"
	@echo "... rubiksCube.i"
	@echo "... rubiksCube.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

